name: Publish Release

on:
  create:
    tags:
      - '\d+\.\d+\.\d+'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

      - uses: actions/setup-java@v4
        if: ${{ vars.GRADLE_JAVA_VERSION != vars.JAVA_VERSION }}
        with:
          distribution: ${{ vars.JAVA_VENDOR }}
          java-version: ${{ vars.GRADLE_JAVA_VERSION }}
          java-package: jre
          cache: 'gradle'

      - run: printf "org.gradle.java.home=%s" "$JAVA_HOME" > gradle.properties
        if: ${{ vars.GRADLE_JAVA_VERSION != vars.JAVA_VERSION }}

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ vars.JAVA_VENDOR }}
          java-version: ${{ vars.JAVA_VERSION }}
          check-latest: true

      - run: printf "\norg.gradle.java.installations.paths=%s" "$JAVA_HOME" >> gradle.properties

      - run: printf "org.gradle.java.home=%s" "$JAVA_HOME" > gradle.properties
        if: ${{ vars.GRADLE_JAVA_VERSION == vars.JAVA_VERSION }}

      - run: java --version

      - name: Gradle Check
        run: ./gradlew check -PtargetJava=${{ vars.JAVA_VERSION }} --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Github Packages
        run: ./gradlew -PtargetJava=${{ vars.JAVA_VERSION }} :core:publish :rpc:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
